config/routes.rb
PollSystem::Application.routes.draw do
  devise_for :users
  resources :users do
    member do
      get :index
    end
  end

  root to: "topics#index"

  match '/home', to: 'static_pages#home'
  match '/help',  to: 'static_pages#help'
  match '/about',  to: 'static_pages#about'
  match '/contact',  to: 'static_pages#contact'
  resources :options
  
  resources :topics do
    member do 
      post :vote
      get :embed
      post :embed_execute
    end
    resources :options
  end

  resources :static_pages  

  resources :topics do
    resources :options
  end

  resources :topics do
    resources :comments
  end

  resources :users do
    resources :comments
  end

  resources :users do
    resources :topics
  end

end

app/models/topic.rb
class Topic
  include Mongoid::Document
  include Mongoid::Timestamps
  attr_accessor :choosen_option
  
  field :name, type: String
  validates :name, presence: true


  has_many :options
  belongs_to :user
  has_many :comments
  
  validates :user_id, presence: true

  paginates_per 6

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def embed
    @topic = Topic.find(params[:id])
    render action: "embed", :layout => "embed.html" 
  end

  def embed_execute
    if params[:topic] == nil
      redirect_to embed_topic_path
      flash[:notice1] = "You must chose an option!"
    else
      @option = Option.find(params[:topic][:choosen_option])
      @option.vote = @option.vote + 1
      if @option.save
        flash[:notice2] = "Thanks for your vote!"
        redirect_to embed_topic_path
      else
        redirect_to embed_topic_path
      end
    end
  end
  # GET /topics
  # GET /topics.json
  def index
    @count = Topic.all.count
    if @count != 0   
    @topics = Topic.desc(:created_at).page params[:page]
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])
    @users = User.all
    @comments = @topic.comments.desc(:created_at).page(params[:page]).per(2)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    if current_user == nil
      redirect_to  user_session_path
      flash[:notice] = "You must sign in to create poll!"
    else
      @topic = Topic.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @topic }
      end
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create1
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /topics
  # POST /topics.json
  def create
    if current_user == nil
      redirect_to  user_session_path
      flash[:notice] = "You must sign in to create poll!"
    else
      @user = current_user
      @topic = @user.topics.create(params[:topic])
      redirect_to topic_path(@topic)  
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy

    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|  
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end

  def vote
    if params[:topic] == nil
      redirect_to topics_path
      flash[:notice] = "You must chose an option!"
    else
      @option = Option.find(params[:topic][:choosen_option])
      @option.vote = @option.vote + 1
      if @option.save
        flash[:success] = "Thanks for your vote!"
        redirect_to topics_path
      else
        redirect_to topics_path
      end
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"Title Topic" %><br />
    <%= f.text_area :name, :placeholder => "Please enter topic..." %>
  </div>
  
  <div class="actions">
    <%= f.submit  :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>
<p>
	<i>Edit Option:</i><br>
		<% @topic.options.each do |o| %>
		<%= o.content %>
		<%= link_to 'Edit', edit_option_path(o)%><br>
		<% end %>
</p>
<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/embed.html.erb
<!-- script for result -->    
<script type = 'text/javascript'>
  $(document).ready(function(){
  $(".btn<%= @topic.id%>").click(function(){
      $(".result<%= @topic.id%>").slideToggle("slow");
      $(".option<%= @topic.id%>").toggle();
    });
  });  
</script>
<style type="text/css">
  div.result<%= @topic.id %>{
    display: none;
  }
</style>

<div class="hero-unit-1">
  <% if flash[:notice1] %>
    <div id="notice1" class = "alert alert-error"><%= flash[:notice1] %></div>
    <% else %>
    <%if flash[:notice2]%>
    <div id="notice2" class = "alert alert-success"><%= flash[:notice2] %></div>
    <% end %>
  <% end %>
  
        <ol>
          <li>
            <%= @topic.name %>  
            <div class="result<%= @topic.id %>">
              <% @total = 0 %> <!-- total votes of one topic -->
              <% @topic.options.each do |o| %>
                <% @total = @total + o.vote %>
              <% end %>
              <% @topic.options.each do |o| %>
                <%= o.content %> ( <%= o.vote %> vote )
                <% if @total == 0 %>
                 <% @percen = 0 %>
                <% else %>
                <% @percen = 100*o.vote/@total %>
                <% end %>
                <div class = 'progress' >
                  <div class = 'bar' style = "width: <%= @percen %>%;">
                    <%= @percen %>%
                  </div>
                </div> 
              <% end %>
              <div>Total : <%= @total %> vote<br/><br/></div>
            </div>
            <div class="option<%= @topic.id %>">
              <%= form_for @topic, url: embed_execute_topic_path(@topic), method: :post do |f|%>
              <% @topic.options.each do |o| %>
                <%= f.radio_button :choosen_option, o.id %><%= o.content %><br>
              <% end %>
              
              <div class="actions">
                <button class = "btn btn-primary">Vote</button>
                <a class="btn<%= @topic.id%>" role="button" >Results</a><br>
              </div>  
              <% end %>
            </div>
          </li> 
      </ol>
      </div>

app/views/topics/index.html.erb
<script src = 'app/assets/javascripts/bootstrap-modal.js'></script>
<div class="hero-unit">
      <center>
      <p>Wellcome to poll system. You can quickly create poll and embed to your website.</p>
      </center>
      <center>
      <p><%= link_to 'CREATE NOW', new_topic_path, :class => "btn btn-primary btn-large" %><p></center>
</div>


 <% @topics.each_slice(3) do |group_of_3| %>
    <div class="row-fluid">
    <% group_of_3.each do |topic| %>
      <div class="hero-unit-1 span4">
        <ul>
          <li>
            <div id="<%= topic.id%>" class="modal hide fade in"  >
              <div class="modal-header">
                <%= topic.name %>  
              </div>
              <div class="modal-body">
                <% @total = 0 %> <!-- total votes of one topic -->
                <% topic.options.each do |o| %>
                  <% @total = @total + o.vote %>
                <% end %>
                <% topic.options.each do |o| %>
                  <%= o.content %> (<%= o.vote %> vote)
                  <% if @total == 0 %>
                   <% @percen = 0 %>
                  <% else %>
                  <% @percen = 100*o.vote/@total %>
                  <% end %>
                  <div class = 'progress' >
                    <div class = 'bar' style = "width: <%= @percen %>%;">
                      <%= @percen %>%
                    </div>
                  </div> 
                <% end %>
                <div>Total : <%= @total %> vote<br/><br/></div>
              </div>
              <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
              </div>
            </div>
            <div class="option<%= topic.id %>">
              <%= topic.name %>
              <%= form_for topic, url: vote_topic_path(topic), method: :post do |f|%>
              <% topic.options.each do |o| %>
                <%= f.radio_button :choosen_option, o.id %><%= o.content %><br>
              <% end %>
              
              <div class="actions">
                <button class = "btn btn-primary">Vote</button>
                <a class="btn" href="#<%= topic.id%>"  data-toggle="modal">Results</a><br>
              </div>  
              <% end %>
            </div>
            <div class="field">
              Embed code : <br>  
              <input value="<iframe framboder=0 scrolling='yes' height='300px' width='600px' src='http://localhost:3000/topics/<%= topic.id %>/embed'></iframe>  ">
            </div>    
            <%= link_to 'Comment', topic %>
            <% if current_user != nil and current_user.email == "admin@poll.com" %>
            <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </li> 
      </ul>
    </div>
    <% end %>
  </div>
<% end %><!-- End .row-fluid -->
<div class="paginate"><%= paginate @topics %></div>

app/views/topics/new.html.erb
<div class="container-fluid">
  	<div class="row-fluid">
	    <div class="span3">
	    	<!--Sidebar content-->
	      	<%= render 'share/menu' %>
	    </div>
	    <div class="hero-unit-1 span9">
			<%= render 'form' %>
	    </div>
	</div>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="hero-unit-1 span6">
  	Topic: <%= @topic.name %>
  		<div class="result">
              <% @total = 0 %> <!-- total votes of one topic -->
              <% @topic.options.each do |o| %>
                <% @total = @total + o.vote %>
              <% end %>
              <% @topic.options.each do |o| %>
                <%= o.content %> (<%= o.vote %> vote)
                <% if @total == 0 %>
                 <% @percen = 0 %>
                <% else %>
                <% @percen = 100*o.vote/@total %>
                <% end %>
                <div class = 'progress' >
                  <div class = 'bar' style = "width: <%= @percen %>%;">
                    <%= @percen %>%
                  </div>
                </div> 
              <% end %>
            <div>Total : <%= @total %> vote<br/><br/></div>
     	</div>	
  </div>

<% if current_user && current_user.id == @topic.user_id %>
  	<div class="hero-unit-1 span5">
	  	<p>Create options for topics</p>
		<%=	 form_for([@topic, @topic.options.build]) do |f| %>
			<div class="field">
				<%= f.text_field :content %>	
			</div>
			<div class="actions">
				<button class = "btn btn-primary">Creat</button>
				<%= link_to 'Back',  users_path, :class => "btn btn-primary" %>
			</div>
		<% end %>
	</div>
<% else %>
	<div class="hero-unit-1 span5">
	    <center>
	    	<p>Wellcome to poll system. You can quickly create poll and embed to your website.</p>
	    </center>
	    <center>
	    	<p><%= link_to 'CREATE NOW', new_topic_path, :class => "btn btn-primary btn-large" %><p>	    		
	    </center>
	</div>
<% end %>

<div class="hero-unit-1 span6">
	<% @topic.comments.each do |comment| %>
	  	<% if comment.user_id == "123456" %>
	      <%= image_tag("/assets/ava.jpg",:height => '80', :class => 'gravatar', :position => 'absolute') %>&nbsp;&nbsp;<%= comment.c_content %> <hr />
	  	<% end %>
	   	<% @users.each do |u| %>  
	      	<% if comment.user_id == u.id %>
	       		<%= gravatar_for u %>&nbsp;&nbsp;<%= comment.c_content %><hr />
	    	<% end %>    
	   	<% end %>   
	<% end %>
</div>
<div class="hero-unit-1 span6">
	  	<p>Create comment for topics</p>
		<%=	 form_for([@topic, @topic.comments.build]) do |c| %>
			<div class="field">
				<%= c.text_area :c_content %>	
				<% if current_user %>
					<div style="float: left; margin-right: 25px; height: 90px;"><%= gravatar_for current_user %></div>
				<% else %>
					<div style="float: left; margin-right: 25px; height: 90px;"><%= image_tag("/assets/ava.jpg", :size => 50) %></div>
				<% end %>		
			</div>

			<div class="actions">
				<button class = "btn btn-primary" >Comment</button>
			</div>
		<% end %>
</div>
</div>