config/routes.rb
PollSystem::Application.routes.draw do
  devise_for :users
  resources :users do
    member do
      get :index
    end
  end

  root to: "topics#index"

  match '/home', to: 'static_pages#home'
  match '/help',  to: 'static_pages#help'
  match '/about',  to: 'static_pages#about'
  match '/contact',  to: 'static_pages#contact'
  resources :options
  
  resources :topics do
    member do 
      post :vote
      get :embed
      post :embed_execute
    end
    resources :options
  end

  resources :static_pages  

  resources :topics do
    resources :options
  end

  resources :topics do
    resources :comments
  end

  resources :users do
    resources :comments
  end

  resources :users do
    resources :topics
  end

end

app/models/option.rb
class Option
  include Mongoid::Document
  field :content, type: String
  field :vote, type: Integer, :default => 0
  validates :content, presence: true
  validates :vote, presence: true
  validates :topic_id, presence: true
  
  belongs_to :topic
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  # GET /options
  # GET /options.json
  def index
    @options = Option.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @options }
    end
  end

  # GET /options/1
  # GET /options/1.json
  def show
    @option = Option.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/new
  # GET /options/new.json
  def new
    @option = Option.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/1/edit
  def edit
    @option = Option.find(params[:id])
  end

  # POST /options
  # POST /options.json

  def create
    @topic = Topic.find(params[:topic_id])
    @option = @topic.options.create(params[:option])
    redirect_to topic_path(@topic)
  end

  # PUT /options/1
  # PUT /options/1.json
  def update
    @option = Option.find(params[:id])

    respond_to do |format|
      if @option.update_attributes(params[:option])
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option = Option.find(params[:id])
    @option.destroy

    respond_to do |format|
      format.html { redirect_to options_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/options/_form.html.erb
<%= form_for(@option) do |f| %>
  <% if @option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
      <% @option.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :vote %><br />
    <%= f.number_field :vote %>
  </div>
  <div class="actions">
    <button class = "btn btn-primary">Creat</button>
  </div>
<% end %>

app/views/options/edit.html.erb
<h1>Editing option</h1>

<%= render 'form' %>

<%= link_to 'Show', @option %> |
<%= link_to 'Back', options_path %>

app/views/options/index.html.erb
<h1>Listing options</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Vote</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @options.each do |option| %>
  <tr>
    <td><%= option.content %></td>
    <td><%= option.vote %></td>
    <td><%= link_to 'Show', option %></td>
    <td><%= link_to 'Edit', edit_option_path(option) %></td>
    <td><%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Option', new_option_path %>

app/views/options/new.html.erb
<h1>New option</h1>

<%= render 'form' %>

<%= link_to 'Back', options_path %>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @option.content %>
</p>

<p>
  <b>Vote:</b>
  <%= @option.vote %>
</p>


<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>