config/routes.rb
PollSystem::Application.routes.draw do
  devise_for :users
  resources :users do
    member do
      get :index
    end
  end

  root to: "topics#index"

  match '/home', to: 'static_pages#home'
  match '/help',  to: 'static_pages#help'
  match '/about',  to: 'static_pages#about'
  match '/contact',  to: 'static_pages#contact'
  resources :options
  
  resources :topics do
    member do 
      post :vote
      get :embed
      post :embed_execute
    end
    resources :options
  end

  resources :static_pages  

  resources :topics do
    resources :options
  end

  resources :topics do
    resources :comments
  end

  resources :users do
    resources :comments
  end

  resources :users do
    resources :topics
  end

end

app/views/layouts/_footer.html.erb
<hr>
<footer class="container">
  <small>
    Deverlop by TDT
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Poll System", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", topics_path %></li>
          <li><%= link_to "About",   about_path %></li>                      
          <% if signed_in? %>
            <li><%= link_to current_user.email, users_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>             
            <li><%= link_to "Sign Up",  new_user_registration_path %></li>
          <% end %>          
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>  

  </head>
  <body class="stardand">
    <%= render 'layouts/header' %>
    <div class="container">
        <% if flash[:notice] %>
          <div id="notice1" class = "alert alert-error"><%= flash[:notice] %></div>
        <% end %>
        <% if flash[:success] %>
          <div id="notice1" class = "alert alert-success"><%= flash[:success] %></div>
        <% end %>

        <%= yield %>          
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/embed.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>  
    <%= yield %>
  </head>
</html>